//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceExercise.TemperatureServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TemperatureServiceReference.TempWebServiceSoap")]
    public interface TempWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServiceExercise.TemperatureServiceReference.HelloWorldResponse HelloWorld(WebServiceExercise.TemperatureServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceExercise.TemperatureServiceReference.HelloWorldResponse> HelloWorldAsync(WebServiceExercise.TemperatureServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFahrenheit", ReplyAction="*")]
        double CelsiusToFahrenheit(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToKelvin", ReplyAction="*")]
        double CelsiusToKelvin(double celsuis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToKelvin", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CelsiusToKelvinAsync(double celsuis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelsius", ReplyAction="*")]
        double FahrenheitToCelsius(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToKelvin", ReplyAction="*")]
        double FahrenheitToKelvin(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToKelvin", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FahrenheitToKelvinAsync(double fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KelvinToCelsius", ReplyAction="*")]
        double KelvinToCelsius(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KelvinToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<double> KelvinToCelsiusAsync(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KelvinToFahrenheit", ReplyAction="*")]
        double KelvinToFahrenheit(double kelvin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KelvinToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> KelvinToFahrenheitAsync(double kelvin);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceExercise.TemperatureServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceExercise.TemperatureServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceExercise.TemperatureServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceExercise.TemperatureServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TempWebServiceSoapChannel : WebServiceExercise.TemperatureServiceReference.TempWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TempWebServiceSoapClient : System.ServiceModel.ClientBase<WebServiceExercise.TemperatureServiceReference.TempWebServiceSoap>, WebServiceExercise.TemperatureServiceReference.TempWebServiceSoap {
        
        public TempWebServiceSoapClient() {
        }
        
        public TempWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TempWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TempWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceExercise.TemperatureServiceReference.HelloWorldResponse WebServiceExercise.TemperatureServiceReference.TempWebServiceSoap.HelloWorld(WebServiceExercise.TemperatureServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServiceExercise.TemperatureServiceReference.HelloWorldRequest inValue = new WebServiceExercise.TemperatureServiceReference.HelloWorldRequest();
            inValue.Body = new WebServiceExercise.TemperatureServiceReference.HelloWorldRequestBody();
            WebServiceExercise.TemperatureServiceReference.HelloWorldResponse retVal = ((WebServiceExercise.TemperatureServiceReference.TempWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceExercise.TemperatureServiceReference.HelloWorldResponse> WebServiceExercise.TemperatureServiceReference.TempWebServiceSoap.HelloWorldAsync(WebServiceExercise.TemperatureServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceExercise.TemperatureServiceReference.HelloWorldResponse> HelloWorldAsync() {
            WebServiceExercise.TemperatureServiceReference.HelloWorldRequest inValue = new WebServiceExercise.TemperatureServiceReference.HelloWorldRequest();
            inValue.Body = new WebServiceExercise.TemperatureServiceReference.HelloWorldRequestBody();
            return ((WebServiceExercise.TemperatureServiceReference.TempWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public double CelsiusToFahrenheit(double celsius) {
            return base.Channel.CelsiusToFahrenheit(celsius);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsius) {
            return base.Channel.CelsiusToFahrenheitAsync(celsius);
        }
        
        public double CelsiusToKelvin(double celsuis) {
            return base.Channel.CelsiusToKelvin(celsuis);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToKelvinAsync(double celsuis) {
            return base.Channel.CelsiusToKelvinAsync(celsuis);
        }
        
        public double FahrenheitToCelsius(double fahrenheit) {
            return base.Channel.FahrenheitToCelsius(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double fahrenheit) {
            return base.Channel.FahrenheitToCelsiusAsync(fahrenheit);
        }
        
        public double FahrenheitToKelvin(double fahrenheit) {
            return base.Channel.FahrenheitToKelvin(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToKelvinAsync(double fahrenheit) {
            return base.Channel.FahrenheitToKelvinAsync(fahrenheit);
        }
        
        public double KelvinToCelsius(double kelvin) {
            return base.Channel.KelvinToCelsius(kelvin);
        }
        
        public System.Threading.Tasks.Task<double> KelvinToCelsiusAsync(double kelvin) {
            return base.Channel.KelvinToCelsiusAsync(kelvin);
        }
        
        public double KelvinToFahrenheit(double kelvin) {
            return base.Channel.KelvinToFahrenheit(kelvin);
        }
        
        public System.Threading.Tasks.Task<double> KelvinToFahrenheitAsync(double kelvin) {
            return base.Channel.KelvinToFahrenheitAsync(kelvin);
        }
    }
}
